### ISSUE TITLE
Logging should be standarized across network. 

### ISSUE THREAD

**Issue by umesh-timalsina** [oele-isis-vanderbilt/ChimeraPy#111]
I think taking some inspiration from the logging cookbook in python, we can devise something like a networked logger module in python that can be leveraged by the p2p network to manage and handle logging across the network into a centralized entity. 

It can contain multiple pull sockets that the clients in the p2p network can push to for logging.

The initial attempt is to achieve the following:
- A manager can optionally choose to have some pull sockets that the workers can push(raw logs) to.
- A worker when connected to the manager will receive the information about the zmq pull sockets that they can leverage to add push sockets to send logs via the p2p network.
- Intially everything can be pushed/pulled as strings.
- The push-pull socket can be used to then create different loggers that will have added a single handler to publish logs to the zmq socket.
- Optionally we can extend it to send LogRecords over the p2p network, such that structured log monitoring can be done (sending it to an external service).

**Comment by edavalosanaya** [comment]
Agreed that centralizing the logs by sending them to the ``Manager`` would be ideal. Not sure if we want to use PUSH/PULL pattern, since the default zeromq log handler uses the PUB/SUB design pattern: https://pyzmq.readthedocs.io/en/latest/api/zmq.log.handlers.html

**Comment by umesh-timalsina** [comment]
I think a push-pull makes more sense. Because it's up to the `Manager` to delegate a consumer of log records and the workers can query/ get that info upon connection. So, here is what I am thinking. This is the underlying service but the messaging is what 
starts the logging.
![chimerapy distributed_logging](https://user-images.githubusercontent.com/11476842/220468710-0cc1347f-5ab9-4e2b-a46d-c5c5770491a5.png)

**Comment by umesh-timalsina** [comment]
Bringing over a conversation with @edavalosanaya from slack here. If we are to proceed with this idea, we need to proceed with the following steps:

1. Refactor the current logging implementation to use a `QueueHandler` and a `QueueListener`. This is nice because its runs in a separate thread (which will be crucial for non-blocking logs). Not sure if we can get away with using a normal Queue or might have to use other `mp.Queue`.

2. Change the logger's identification for workers/nodes based either on UUID module level names. Currently, I find it difficult to understand the originator of the log message. I want to do this in a modular way such that if we comeup with something generic, we can levarage this framework for analyzing other kind of data (basically, leverage the logRecords somehow.)

3. Finally, integrate the distributed logging idea by replacing the queue with a zero message Queue.

**Comment by umesh-timalsina** [comment]
Since this is already a distributed framework, we can just get away with a module called `chimerapy.logging`

**Comment by edavalosanaya** [comment]
This is a reference about how to be implemented: https://docs.python.org/3/howto/logging-cookbook.html#subclassing-queuelistener-a-zeromq-example

**Comment by edavalosanaya** [comment]
Closed by PR#125
