### ISSUE TITLE
ChimeraPy Node shouldn't subclass a Process

### ISSUE THREAD

**Issue by umesh-timalsina** [oele-isis-vanderbilt/ChimeraPy#131]
It might be nice to make sure that a worker has a process pool executor where it executes the nodes rather than us subclassing a whole process. This might be easier to do if we eventually move to a code generation and delivery mechanism rather than a pickle route. The advantage includes that we don't have to worry about interacting with those pesky OS-specific constructs on the lowest level.

@edavalosanaya Thoughts on this? How big of an undertaking do you think this will end up being?

**Comment by edavalosanaya** [comment]
I second the notion that we need to transition from `mp.Process` to a process pool executor. Making this change is risky thereby making a time estimate difficult to pinpoint. Regardless, I think this is an essential maintenance task we need to address eventually. We can tackle this issue after we address ASAP-needed features (#111, #103, #86, #69, #134).
