### ISSUE TITLE
Destroying Nodes should broadcast NetworkStatus Update

### ISSUE THREAD

**Issue by umesh-timalsina** [oele-isis-vanderbilt/ChimeraPy#193]
It looks like async_reset doesn't broadcast the latest status of the manager.

**Comment by umesh-timalsina** [comment]
I also noticed that the manager becomes stale i.e. deleted nodes aren't actually removed from the state even though the state from workers seems to update properly.

**Comment by edavalosanaya** [comment]
Closed by #196
