### ISSUE TITLE
Allow Manager's `logdir` argument to also accept a string

### ISSUE THREAD

**Issue by umesh-timalsina** [oele-isis-vanderbilt/ChimeraPy#81]
Currently, the `logdir` only accepts a `pathlib.Path`. Would it make sense to allow a string as well as it is more convenient IMO?

**Comment by edavalosanaya** [comment]
That's a good point! We can make it a `Union[pathlib.Path, str]` and then just convert it to a ``pathlib.Path`` object if the input is a string.
