### ISSUE TITLE
Manager's server should also be available on `localhost`

### ISSUE THREAD

**Issue by umesh-timalsina** [oele-isis-vanderbilt/ChimeraPy#93]
This is primarily related to developing the dashboard api. Currently, to skirt `cors` , I am using `vite's` [proxy config](https://github.com/oele-isis-vanderbilt/ChimeraPy/blob/e2d69575ceec3d67943337aeb650f02c2fd29d34/chimerapy/dashboard/vite.config.ts#L11-L18), where in we have to redirect the request via a URL. However, the manager's server is unavailable at `localhost`, which has made me hard-code my IP address, it might be nice to resolve this.

**Comment by edavalosanaya** [comment]
Closed by #95
